version: 2.1

jobs:
  frontend-check:
    docker:
      - image: cimg/node:23.1.0
    steps:
      - checkout
      - run:
          name: Check Node Version
          command: node --version
      - run:
          name: Install Frontend Dependencies
          command: |
            cd tap-client
            npm i
      - run:
          name: Build Frontend Project
          command: |
            cd tap-client
            npm run build
      - run:
          name: Run Frontend Tests
          command: |
            cd tap-client
            npm test

  backend-check:
    docker:
      - image: cimg/node:23.1.0
      - image: circleci/mongo:5.0   
    environment:
      MONGODB_URI: mongodb://localhost:27017/test-db
      JWT_SECRET: test_jwt_secret
      PORT: 3000
    steps:
      - checkout
      - run:
          name: Check Node Version
          command: node --version
      - run:
          name: Install Backend Dependencies
          command: |
            cd tap-api
            npm i
      - run:
          name: Run Backend Linter
          command: |
            cd tap-api
            npm run lint
      - run:
          name: Run Backend Tests
          command: |
            cd tap-api
            npm test
      - run:
          name: Build Backend Project
          command: |
            cd tap-api
            npm run build

workflows:
  version: 2
  project-checks:
    jobs:
      - frontend-check
      - backend-check
