version: 2.1

workflows:
  frontend-tests:
    jobs:
      - frontend-check

jobs:
  frontend-check:
    docker:
      - image: cimg/node:23.1.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd tap-client
            npm install
      - run:
          name: Build Frontend Project
          command: |
            cd tap-client
            npm run build
